version: "3.2"
services:
  web:
    image: ${DOCKER_REPO}:${TIMESTAMP}
    command: /opt/app/bin/sejfguru foreground
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 400M
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.frontend.rule=HostRegexp: ${VIRTUAL_HOST}"
        - "traefik.port=4000"
        - "traefik.docker.network=swarm"
    env_file: /home/deploy/apps/sejfguru/shared/secrets.env
    labels:
      - netguru.appname=sejfguru
      - netguru.stage=staging
    hostname: netguru.sejfguru.staging.web
    networks:
      - swarm
networks:
  swarm:
    external:
      name: swarm
